name: Imprime data atual

on:
  push:
  
jobs:
  imprime_data_ubuntu:
    name: Imprime data atual - Ubuntu
    
    steps:
      - name: Imprime data atual
        run: date
  
  imprime_data_windows:
    name: Imprime data atual - Windows
    runs-on: windows-latest
    
    steps:
      - name: Imprime data atual
        run: date
        
  imprime_data_macos:
    name: Imprime data atual - macos
    runs-on: macos-latest
    
    steps:
      - name: Imprime data atual
        run: date
        
  imprime_data_ubunto_ult:
    name: Imprime data atual - ubunto- ult
    runs-on: ubunto-latest
    needs: 
    - imprime_data_ubuntu
    - imprime_data_windows
    - imprime_data_macos
    
    steps:
      - name: Imprime data atual
        run: date
